# Generated by Django 3.1.2 on 2020-10-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.TextField()),
                ('email', models.TextField(primary_key=True, serialize=False)),
                ('phoneNumber', models.TextField()),
                ('bio', models.TextField()),
            ],
        ),
    ]
